# Generated by Django 4.2.16 on 2025-02-17 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField(unique=True)),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.TextField(choices=[('default', 'Default'), ('tier1', 'Tier 1')], default='default')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bands.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.TextField(choices=[('default', 'Default'), ('tier1', 'Tier 1')])),
                ('band_type', models.TextField(choices=[('salary', 'Salary'), ('equity', 'Equity')])),
                ('min', models.BigIntegerField()),
                ('target', models.BigIntegerField()),
                ('max', models.BigIntegerField()),
                ('currency_code', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bands.organization')),
            ],
        ),
    ]
