# Generated by Django 4.2.16 on 2025-02-17 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FacetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('are_multiple_allowed', models.BooleanField()),
                ('is_required', models.BooleanField()),
                ('facets', models.ManyToManyField(to='bands.facet')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bands.organization')),
            ],
        ),
        migrations.AddField(
            model_name='facet',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bands.facettype'),
        ),
        migrations.AddField(
            model_name='employee',
            name='facets',
            field=models.ManyToManyField(to='bands.facet'),
        ),
    ]
