# Generated by Django 4.2.16 on 2025-02-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_facet_facettype_facet_type_employee_facets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='band_name',
        ),
        migrations.RemoveField(
            model_name='band',
            name='band_type',
        ),
        migrations.RemoveField(
            model_name='facettype',
            name='facets',
        ),
        migrations.AddField(
            model_name='band',
            name='facets',
            field=models.ManyToManyField(to='bands.facet'),
        ),
    ]
