# Generated by Django 4.2.16 on 2025-02-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0004_remove_employee_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
