# Generated by Django 4.2.16 on 2025-02-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0005_employee_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='currency_code',
        ),
        migrations.RemoveField(
            model_name='band',
            name='description',
        ),
        migrations.AddField(
            model_name='band',
            name='band_type',
            field=models.TextField(choices=[('salary', 'Salary'), ('equity', 'Equity')], default=''),
            preserve_default=False,
        ),
    ]
